### PR TITLE
Allow premium accounts to configure consumer_key and consumer_secret instead of bearer token

### PR DESCRIPTION
**Pull request by tonybaloney**
Previous behaviour:
_premium_ users have to specify bearer_token in their credential files

New behaviour:
_premium_ users can specify bearer token as before
they can also use _`consumer_key`_ and _`consumer_secret`_ in the creds YAML file. If this is specified, the `bearer_token` will be set on startup by a helper function inside the credentials submodule.

### CODE REVIEW

**Comment by tonybaloney** [comment]
@binaryaaron

**Comment by binaryaaron** [comment]
Thank you for the PR! I was quite literally adding a bearer token utility to the library and command-line interface. 

I like where this is going, but I'll leave some specific feedback soon.

**Comment by binaryaaron** [comment]
@tonybaloney - can you change the target of this PR to `credential_updates`? I'd like to integrate the bearer token functionality into the command-line app as an explicit command and will update the documentation as well.

**Comment by binaryaaron** [comment]
Hey @tonybaloney - I'd love to merge this if you could change the target branch to `credential_updates` when you get a chance. Thanks!

**Comment by tonybaloney** [comment]
@binaryaaron done

**Comment by binaryaaron** [comment]
Thanks!

**Pull request merged**
